cors:
  originPatterns: http://localhost:8080,http://localhost:3000

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb1
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

flyway:
  url: jdbc:h2:mem
  schemas: testdb1
  user: sa
  password: password
  locations: filesystem:db/migration